<?php
$page_id = 'transferencias';
$page_url = 'transferencias';
$table = 'transferencias';
$page_nome = 'Transferências';
$url_destino = 'transferencias';
$lista_r = new Transferencia(true);
$lista = $lista_r->getListagem($_SESSION['id_registro']);
$case_css = array('datatables.min.css', 'fontawesome.min.css');
$case_js = array('datatables.min.js', 'fontawesome.min.js');

$array_nomes = array(
    'Data e Hora',
    'Enviado por',
    'Recebida por',
    'Valor',
    'STATUS'
);
include_once('view/header.phtml');
?>
<div class="main-content">
    <?php include_once 'view/nav.phtml' ?>
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0"><?php echo $page_nome?></h3>
                        </div>
                        <?php if ($_SESSION['tipo_pessoa'] != 'J') {?>
                        <div class="col-4 text-right">
                            <a href="<?php echo URL_SITE . '/' . $url_destino . '-form' ?>"
                               class="btn btn-sm btn-primary">Adicionar</a>
                        </div>
                        <?php }?>
                    </div>
                </div>
                <div class="table-responsive">
                    <div class="col-12">
                        <table id="dtBasicExample" class="table table-striped table-bordered table-sm"
                               cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <?php foreach ($array_nomes as $n_m){?>
                                    <th scope="th-sm"><?php echo $n_m?></th>
                                <?php }?>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            if ($lista) {
                                foreach ($lista as $u_s) {?>
                                    <tr>
                                        <td><?php echo $u_s->data_hora ?></td>
                                        <td><?php echo utf8_encode($u_s->usuario_envia) ?></td>
                                        <td><?php echo utf8_encode($u_s->usuario_recebe) ?></td>
                                        <td><?php echo ($u_s->id_usuario_envia == $_SESSION['id_registro']) ? '-R$ ' . number_format($u_s->valor,2,",",".") : '+R$ ' . number_format($u_s->valor,2,",","."); ?></td>
                                        <td><?php echo ($u_s->status == 'C') ? 'Concluído' : 'Recusada' ?></td>
                                    </tr>
                                <?php }
                            }else{?>
                                <tr><td colspan="5" class="text-center nulo">Não contém nenhum registro ainda</td></tr>
                            <?php }?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    include_once('view/footer.phtml');
    ?>
    <script type="text/javascript">
        $('#dtBasicExample').DataTable({
            "order": [[ 0, "desc" ]]
        });
        $('.dataTables_length').addClass('bs-select');
    </script>

