<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Leonardo Cruz">
    <title>Carteira Digital</title>
    <link href='<?php echo BASE_SITE_IMG ?>/icon.ico' rel='shortcut' type='image/x-icon'/>
    <link href='<?php echo BASE_SITE_IMG ?>/icon.png' rel='icon' type='image/png'/>
    <link href="<?php echo BASE_SITE_CSS ?>/fontawesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="<?php echo BASE_SITE_CSS?>/fonts.css">
    <link rel="stylesheet" href="<?php echo BASE_SITE_CSS?>/case_css.min.css">
    <link href="<?php echo BASE_SITE_CSS ?>/style.css" rel="stylesheet">
    <?php foreach ($case_css as $css){?>
        <link href="<?php echo BASE_SITE_CSS .'/'.$css?>" rel="stylesheet">
    <?php }?>
</head>
<body <?php echo(isset($page_id) ? 'id="' . $page_id . '"' : '') ?>>
<?php if ($page_id == 'login' || $page_id == 'cadastro'){?>
    <header>
        <div class="header bg-gradient-primary">
            <br />
            <br />
            <div class="py-6 py-lg-5">
                <div class="container">
                    <div class="header-body text-center">
                        <div class="row justify-content-center">
                            <div class="col-lg-6 col-md-6">
                                <h1 class="text-white">Carteira Digital</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="carregar" class="position-center">
            <img src="<?php echo BASE_SITE_IMG ?>/carregar.gif" alt="Loading">
        </div>
        <div id="form_mensagem" class="position-center">
            <div class="mensagem text-center error">
                <span class="mensagem"></span>
                <br />
                <span class="button"></span>
            </div>
        </div>
    </header>
<?php } else {
$paginas = new Paginas();
$usuario_foto = new Usuario();
?>
    <div id="carregar" class="position-center">
        <img src="<?php echo BASE_SITE_IMG ?>/carregar.gif" alt="Loading">
    </div>
    <div id="form_mensagem" class="position-center">
        <div class="mensagem text-center error">
            <span class="mensagem"></span>
            <br />
            <span class="button"></span>
        </div>
    </div>
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-brand pt-0">
                <img src="<?php echo BASE_SITE_IMG ?>/logotipo_color.png" alt="Logotipo">
            </div>
            <ul class="nav align-items-center d-md-none">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                            <img src="<?php echo BASE_SITE_UPLOADS .'/perfil/large/perfil.jpg'?>" alt="Foto do perfil"/>
                        </span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <div class=" dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Olá!</h6>
                        </div>
                        <a href="<?php echo URL_SITE .'/painel'?>" class="dropdown-item">
                            <i class="fas fa-user icone text-info "></i>
                            <span>Meu perfil</span>
                        </a>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users icone text-success "></i>
                            <span>Apoio, suporte</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-item" id="sair">
                            <i class="fas fa-ban icone text-red"></i>
                            <span>Sair</span>
                        </div>
                    </div>
                </li>
            </ul>
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <div>
                                <img src="<?php echo BASE_SITE_IMG ?>/logotipo_color.png">
                            </div>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo URL_SITE?>/home">
                            <i class="icon painel"></i> Painel
                        </a>
                    </li>
                    <?php
                        $pagina_superior = $paginas->get_lista('S');
                        foreach ($pagina_superior as $ps){
                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo URL_SITE .'/'.$ps->url_destino?>-lista">
                            <i class="icon usuario"></i> <?php echo utf8_encode($ps->nome)?>
                        </a>
                    </li>
                    <?php }?>
                </ul>
                <hr class="my-3" />
                <h6 class="navbar-heading text-muted">Páginas</h6>
                <ul class="navbar-nav mb-md-3">
                    <?php $pagina_inferior = $paginas->get_lista('I');
                    foreach ($pagina_inferior as $pi){

                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo URL_SITE .'/'.$pi->url_destino?>-lista">
                            <i class="icon vendas"></i> <?php echo utf8_encode($pi->nome)?>
                        </a>
                    </li>
                    <?php }?>
                </ul>
            </div>
        </div>
    </nav>
<?php } ?>



